# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mlueckhof/Codes/Projects/Geant/PhotonStopper/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mlueckhof/Codes/Projects/Geant/PhotonStopper/source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mlueckhof/Codes/Projects/Geant/PhotonStopper/source/CMakeFiles /home/mlueckhof/Codes/Projects/Geant/PhotonStopper/source/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mlueckhof/Codes/Projects/Geant/PhotonStopper/source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named examplePhST

# Build rule for target.
examplePhST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examplePhST
.PHONY : examplePhST

# fast build rule for target.
examplePhST/fast:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/build
.PHONY : examplePhST/fast

examplePhST.o: examplePhST.cc.o

.PHONY : examplePhST.o

# target to build an object file
examplePhST.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/examplePhST.cc.o
.PHONY : examplePhST.cc.o

examplePhST.i: examplePhST.cc.i

.PHONY : examplePhST.i

# target to preprocess a source file
examplePhST.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/examplePhST.cc.i
.PHONY : examplePhST.cc.i

examplePhST.s: examplePhST.cc.s

.PHONY : examplePhST.s

# target to generate assembly for a file
examplePhST.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/examplePhST.cc.s
.PHONY : examplePhST.cc.s

src/PhSTActionInitialization.o: src/PhSTActionInitialization.cc.o

.PHONY : src/PhSTActionInitialization.o

# target to build an object file
src/PhSTActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTActionInitialization.cc.o
.PHONY : src/PhSTActionInitialization.cc.o

src/PhSTActionInitialization.i: src/PhSTActionInitialization.cc.i

.PHONY : src/PhSTActionInitialization.i

# target to preprocess a source file
src/PhSTActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTActionInitialization.cc.i
.PHONY : src/PhSTActionInitialization.cc.i

src/PhSTActionInitialization.s: src/PhSTActionInitialization.cc.s

.PHONY : src/PhSTActionInitialization.s

# target to generate assembly for a file
src/PhSTActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTActionInitialization.cc.s
.PHONY : src/PhSTActionInitialization.cc.s

src/PhSTDetectorConstruction.o: src/PhSTDetectorConstruction.cc.o

.PHONY : src/PhSTDetectorConstruction.o

# target to build an object file
src/PhSTDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorConstruction.cc.o
.PHONY : src/PhSTDetectorConstruction.cc.o

src/PhSTDetectorConstruction.i: src/PhSTDetectorConstruction.cc.i

.PHONY : src/PhSTDetectorConstruction.i

# target to preprocess a source file
src/PhSTDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorConstruction.cc.i
.PHONY : src/PhSTDetectorConstruction.cc.i

src/PhSTDetectorConstruction.s: src/PhSTDetectorConstruction.cc.s

.PHONY : src/PhSTDetectorConstruction.s

# target to generate assembly for a file
src/PhSTDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorConstruction.cc.s
.PHONY : src/PhSTDetectorConstruction.cc.s

src/PhSTDetectorMessenger.o: src/PhSTDetectorMessenger.cc.o

.PHONY : src/PhSTDetectorMessenger.o

# target to build an object file
src/PhSTDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorMessenger.cc.o
.PHONY : src/PhSTDetectorMessenger.cc.o

src/PhSTDetectorMessenger.i: src/PhSTDetectorMessenger.cc.i

.PHONY : src/PhSTDetectorMessenger.i

# target to preprocess a source file
src/PhSTDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorMessenger.cc.i
.PHONY : src/PhSTDetectorMessenger.cc.i

src/PhSTDetectorMessenger.s: src/PhSTDetectorMessenger.cc.s

.PHONY : src/PhSTDetectorMessenger.s

# target to generate assembly for a file
src/PhSTDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTDetectorMessenger.cc.s
.PHONY : src/PhSTDetectorMessenger.cc.s

src/PhSTPrimaryGeneratorAction.o: src/PhSTPrimaryGeneratorAction.cc.o

.PHONY : src/PhSTPrimaryGeneratorAction.o

# target to build an object file
src/PhSTPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTPrimaryGeneratorAction.cc.o
.PHONY : src/PhSTPrimaryGeneratorAction.cc.o

src/PhSTPrimaryGeneratorAction.i: src/PhSTPrimaryGeneratorAction.cc.i

.PHONY : src/PhSTPrimaryGeneratorAction.i

# target to preprocess a source file
src/PhSTPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTPrimaryGeneratorAction.cc.i
.PHONY : src/PhSTPrimaryGeneratorAction.cc.i

src/PhSTPrimaryGeneratorAction.s: src/PhSTPrimaryGeneratorAction.cc.s

.PHONY : src/PhSTPrimaryGeneratorAction.s

# target to generate assembly for a file
src/PhSTPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhSTPrimaryGeneratorAction.cc.s
.PHONY : src/PhSTPrimaryGeneratorAction.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/examplePhST.dir/build.make CMakeFiles/examplePhST.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... examplePhST"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... examplePhST.o"
	@echo "... examplePhST.i"
	@echo "... examplePhST.s"
	@echo "... src/PhSTActionInitialization.o"
	@echo "... src/PhSTActionInitialization.i"
	@echo "... src/PhSTActionInitialization.s"
	@echo "... src/PhSTDetectorConstruction.o"
	@echo "... src/PhSTDetectorConstruction.i"
	@echo "... src/PhSTDetectorConstruction.s"
	@echo "... src/PhSTDetectorMessenger.o"
	@echo "... src/PhSTDetectorMessenger.i"
	@echo "... src/PhSTDetectorMessenger.s"
	@echo "... src/PhSTPrimaryGeneratorAction.o"
	@echo "... src/PhSTPrimaryGeneratorAction.i"
	@echo "... src/PhSTPrimaryGeneratorAction.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

